# Generated by Django 5.1.6 on 2025-03-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名稱")),
                ("breed", models.CharField(max_length=100, verbose_name="品種")),
                ("price", models.CharField(max_length=20, verbose_name="價格")),
                (
                    "status",
                    models.CharField(
                        default="可預購", max_length=20, verbose_name="狀態"
                    ),
                ),
                (
                    "statusClass",
                    models.CharField(
                        default="status-available",
                        max_length=20,
                        verbose_name="狀態樣式類別",
                    ),
                ),
                (
                    "vaccine",
                    models.CharField(
                        default="已完成基礎疫苗",
                        max_length=100,
                        verbose_name="疫苗情況",
                    ),
                ),
                ("image", models.CharField(max_length=255, verbose_name="圖片路徑")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dogs", "狗狗"),
                            ("cats", "貓咪"),
                            ("small", "小型寵物"),
                        ],
                        max_length=20,
                        verbose_name="分類",
                    ),
                ),
                ("description", models.TextField(verbose_name="描述")),
            ],
        ),
    ]
